In [55]:
from sklearn import datasets
from sklearn import naive_bayes
from sklearn import model_selection
from sklearn import metrics
import numpy as np

In [56]:
x=datasets.load_iris()
x_train,x_test,y_train,y_test=model_selection.train_test_split(x.data,x.target,test_size=0.3,shuffle=True)

In [57]:
# GaussianNB
gaussion_bn=naive_bayes.GaussianNB()
gaussion_bn.fit(x_train,y_train)
print(gaussion_bn.score(x_test,y_test))
print(gaussion_bn.predict_proba(x_test)[:5])
predict_gaussion=gaussion_bn.predict(x_test)
#print(predict[:5])
#print(y_test[:5])
index_guasssion=np.where(predict_gaussion!=y_test)
print(predict[index_guasssion])
print(y_test[index_guasssion])
print(metrics.accuracy_score(y_test,predict_gaussion))

1.0
[[8.25782573e-086 9.99756288e-001 2.43712468e-004]
 [3.26224141e-194 2.99743586e-005 9.99970026e-001]
 [1.46251527e-104 9.89201832e-001 1.07981682e-002]
 [1.00000000e+000 1.24720023e-015 1.95743258e-022]
 [3.28261530e-106 9.92322007e-001 7.67799333e-003]]
[]
[]
1.0


In [58]:
# MultinomialNB
multinomial_nb = naive_bayes.MultinomialNB(alpha=1.0)
multinomial_nb.fit(x_train,y_train)
print(multinomial_nb.score(x_test,y_test))
print(multinomial_nb.predict_log_proba(x_test)[:5])
predict_multinomial=multinomial_nb.predict(x_test)
index_multinomial=np.where(y_test!=predict_multinomial)
print(y_test[index_multinomial])
print(predict_multinomial[index_multinomial])

0.9555555555555556
[[-2.98358521 -0.70126055 -0.79091611]
 [-4.36236497 -0.72438555 -0.68790188]
 [-3.04153522 -0.68460687 -0.80307355]
 [-0.39565336 -1.57026781 -2.13056225]
 [-3.55428096 -0.71339469 -0.73101517]]
[2 2]
[1 1]


In [59]:
# ComplementNB
complement_nb = naive_bayes.ComplementNB(alpha=1.0)
complement_nb.fit(x_train,y_train)
print(complement_nb.score(x_test,y_test))
print(complement_nb.predict_log_proba(x_test)[:5])
predict_complement=complement_nb.predict(x_test)
index_complement=np.where(predict_complement!=y_test)
print(predict_complement[index_complement])
print(y_test[index_complement])

0.6666666666666666
[[-1.28664434 -1.13271517 -0.9121827 ]
 [-1.53485086 -1.16632591 -0.74865393]
 [-1.25174665 -1.1498654  -0.92302386]
 [-0.60077997 -1.36187816 -1.63251681]
 [-1.434808   -1.12465547 -0.82765144]]
[2 2 2 2 2 2 2 0 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [60]:
# BernoulliNB
# 因为要求特征都是二值的，所以对各个特征二值化，随便选一个均值，看看效果如何
mean_train=np.mean(x_train)
mean_test=np.mean(x_test)
x_train[np.where(x_train<=mean_train)]=0
x_train[np.where(x_train>mean_train)]=1
x_test[np.where(x_test<=mean_test)]=0
x_test[np.where(x_test>mean_test)]=1
bernoulli_nb = naive_bayes.BernoulliNB(alpha=1.0)
bernoulli_nb.fit(x_train,y_train)
predict_bernoulli=bernoulli_nb.predict(x_test)
print(bernoulli_nb.score(x_test,y_test))
print(bernoulli_nb.predict_log_proba(x_test)[:5])
print('classes:',bernoulli_nb.classes_)
print('class_prior:',bernoulli_nb.class_log_prior_)
print('class_count:',bernoulli_nb.class_count_)
print('feature_count:\n',bernoulli_nb.feature_count_)
print('features_num:',bernoulli_nb.n_features_)
print('feature_log_prob:\n',bernoulli_nb.feature_log_prob_)

0.6666666666666666
[[-4.80739798 -0.69939959 -0.70330386]
 [-4.80739798 -0.69939959 -0.70330386]
 [-4.80739798 -0.69939959 -0.70330386]
 [-0.21997724 -1.83310997 -3.2821491 ]
 [-4.80739798 -0.69939959 -0.70330386]]
classes: [0 1 2]
class_prior: [-1.07044141 -1.09861229 -1.12759983]
class_count: [36. 35. 34.]
feature_count:
 [[36. 17.  0.  0.]
 [35.  0. 32.  0.]
 [34.  2. 34.  0.]]
features_num: 4
feature_log_prob:
 [[-0.02666825 -0.7472144  -3.63758616 -3.63758616]
 [-0.02739897 -3.61091791 -0.11441035 -3.61091791]
 [-0.02817088 -2.48490665 -0.02817088 -3.58351894]]
