In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier,KDTree,NearestNeighbors,BallTree
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn import model_selection

In [2]:
# self_defination

x = [[2,3,4],[5,4,3],[9,6,7],[4,7,8],[8,1,5],[7,2,6]]
def kd_tree(x,k,depth):
    #input:x
    #output:kdtree
    m=len(x)
    if m==1:
        return tuple(x[0])
    index_feature = depth%k
    sort_x = sorted(x,key=lambda xx:xx[index_feature])
    median=(m)//2
    left=[sort_x[i] for i in range(m) if i<median ]
    right=[sort_x[i] for i in range(m) if i>median]
    
    '''
    print('*'*20)
    print(index_feature)
    print(sort_x)
    print(median)
    print(x[median])
    print(left)
    print(right)
    '''
    
    kdtree={(tuple(sort_x[median])):{}}
    if len(left)>0:
        kdtree[(tuple(sort_x[median]))]['left']=kd_tree(left,k,depth+1)
    if len(right)>0:
        kdtree[tuple(sort_x[median])]['right']=kd_tree(right,k,depth+1)
    return kdtree
kdtree=kd_tree(x,3,0)
print(kdtree)

{(7, 2, 6): {'left': {(5, 4, 3): {'left': (2, 3, 4), 'right': (4, 7, 8)}}, 'right': {(9, 6, 7): {'left': (8, 1, 5)}}}}


In [7]:
# sklearn
# create_datasets
x,y = make_classification(n_samples=1000,n_features=10,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [65]:
# KNeighborsClassifier
param_gride={
    'n_neighbors':[10*(i+1) for i in range(5)],
    'algorithm':['auto','kd_tree','ball_tree','brute'],
    'p':[1,2]
}
knn=KNeighborsClassifier()
knns=model_selection.GridSearchCV(knn,param_grid=param_gride)
knns.fit(x_train,y_train)
#print(knns.score(x_test,y_test))
#print(knns.predict(x_test))
#print(knns.best_params_)
#print(knns.cv_results_)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'algorithm': ['auto', 'kd_tree', 'ball_tree', 'brute'],
                         'n_neighbors': [10, 20, 30, 40, 50], 'p': [1, 2]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [66]:
# NearestNeighbors
nn=NearestNeighbors(n_neighbors=20,radius=2.0,algorithm='auto',leaf_size=30,p=2)
nn.fit(x_train,y_train)
#print(nn.kneighbors())
#print(nn.kneighbors_graph())
#print(nn.radius_neighbors_graph())

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                 radius=2.0)

In [67]:
# kd_tree
xx=np.array([[2,3,4],[5,4,3],[9,6,7],[4,7,8],[8,1,5],[7,2,6]])
KDTREE=KDTree(xx,leaf_size=4,p=2)
dis,ind=KDTREE.query(xx[:1],k=2)
print(ind)
print(xx[ind])

[[0 1]]
[[[2 3 4]
  [5 4 3]]]


In [68]:
# ball_tree
ball_tree=BallTree(x_train,leaf_size=600,p=1)
dis,ind=ball_tree.query(x_test[:2],k=2)
for len in ind:
    for col in len:
        print(x_train[col])

[ 0.69757325  0.20261052  0.24705368 -0.70350109 -0.13987349  0.56439366
  0.33629723  0.01455234  0.74678031 -1.27991398]
[ 0.69861587  0.197616   -0.15727986 -1.81441601  0.17759267  0.77523497
 -0.21586387  0.01803868  1.11439505 -1.27386902]
[ 1.8096511  -1.51786648  1.02876812 -0.32839844  0.53453322 -0.50059923
 -0.81538688  1.37423813 -0.01003865 -0.25053073]
[ 1.95423839 -1.74769576  0.11865494 -0.14938674  0.12844358 -0.8149427
 -0.69672081  1.55503445  0.07882043 -0.1074701 ]
